"""测试 masgent.utils 包中的工具函数（适配拆分后结构）"""

import os
import sys
import datetime
import pytest
from pathlib import Path
import numpy as np
from unittest.mock import patch, MagicMock

# 关键修改：直接导入 utils 包（__init__.py）
import masgent.utils as utils


# ---------- fit_eos 测试 ----------
def test_fit_eos():
    """测试 EOS 拟合函数"""
    # 生成随机体积和能量数据（不依赖已移除的 eos_func）
    volumes = np.linspace(90, 170, 10)
    energies = np.random.randn(10) * 0.1  # 模拟噪声

    volumes_fit, energies_fit = utils.fit_eos(volumes, energies)

    assert len(volumes_fit) == 100
    assert len(energies_fit) == 100
    assert volumes_fit[0] >= min(volumes) * 0.99
    assert volumes_fit[-1] <= max(volumes) * 1.01


# ---------- list_files_in_dir 测试 ----------
def test_list_files_in_dir(tmp_path):
    """测试 list_files_in_dir 函数"""
    # 创建测试目录和文件
    subdir = tmp_path / "subdir"
    subdir.mkdir()

    file1 = tmp_path / "file1.txt"
    file1.write_text("content1")
    file2 = tmp_path / "file2.txt"
    file2.write_text("content2")
    subfile = subdir / "subfile.txt"
    subfile.write_text("subcontent")

    result = utils.list_files_in_dir(str(tmp_path))

    assert len(result) >= 3
    filenames = [os.path.basename(p) for p in result]
    assert "file1.txt" in filenames
    assert "file2.txt" in filenames
    assert "subfile.txt" in filenames


# ---------- write_comments 测试 ----------
def test_write_comments_poscar(tmp_path):
    """测试 write_comments 对 POSCAR 文件写入注释"""
    poscar_path = tmp_path / "POSCAR"
    original_content = "# Original comment\n1.0\n0 0 0\n"
    poscar_path.write_text(original_content)

    comment = "# Generated by test"
    utils.write_comments(str(poscar_path), "poscar", comment)

    content = poscar_path.read_text()
    assert content.startswith(comment + "\n")
    assert "1.0" in content.splitlines()[1]


def test_write_comments_incar(tmp_path):
    """测试 write_comments 对 INCAR 文件写入注释"""
    incar_path = tmp_path / "INCAR"
    original_content = "SYSTEM = test\n"
    incar_path.write_text(original_content)

    comment = "# Generated by test"
    utils.write_comments(str(incar_path), "incar", comment)

    content = incar_path.read_text()
    assert content.startswith(comment + "\n")
    assert "SYSTEM = test" in content


def test_write_comments_kpoints(tmp_path):
    """测试 write_comments 对 KPOINTS 文件写入注释"""
    kpoints_path = tmp_path / "KPOINTS"
    original_content = "# Original comment\nAutomatic\n"
    kpoints_path.write_text(original_content)

    comment = "# Generated by test"
    utils.write_comments(str(kpoints_path), "kpoints", comment)

    content = kpoints_path.read_text()
    assert content.startswith(comment + "\n")


def test_write_comments_unknown_type(tmp_path):
    """测试未知文件类型（默认行为：不做修改）"""
    unknown_path = tmp_path / "unknown.log"
    original_content = "some log content\n"
    unknown_path.write_text(original_content)

    comment = "# Generated by test"
    utils.write_comments(str(unknown_path), "unknown", comment)

    content = unknown_path.read_text()
    assert content == original_content


# ---------- generate_submit_script 测试 ----------
def test_generate_submit_script():
    """测试生成 Slurm 提交脚本"""
    script = utils.generate_submit_script()

    assert isinstance(script, str)
    assert "#!/bin/bash" in script
    assert "#SBATCH --partition=normal" in script
    assert "#SBATCH --nodes=1" in script
    assert "#SBATCH --ntasks=8" in script
    assert "#SBATCH --time=01:00:00" in script
    assert "#SBATCH --job-name=masgent_job" in script
    assert "time srun vasp_std > vasp.out" in script


# ---------- generate_batch_script 测试 ----------
def test_generate_batch_script_default():
    """测试默认的批处理脚本生成"""
    script = utils.generate_batch_script()

    assert isinstance(script, str)
    assert "#!/bin/bash" in script
    assert "cp POTCAR_temp" in script
    assert "cp INCAR_temp" in script
    assert "cp KPOINTS_temp" in script
    assert "sbatch submit.sh" in script


def test_generate_batch_script_no_incar():
    """测试不更新 INCAR 的批处理脚本"""
    script = utils.generate_batch_script(update_incar=False)

    assert "cp INCAR_temp" not in script
    assert "cp KPOINTS_temp" in script


def test_generate_batch_script_no_kpoints():
    """测试不更新 KPOINTS 的批处理脚本"""
    script = utils.generate_batch_script(update_kpoints=False)

    assert "cp KPOINTS_temp" not in script
    assert "cp INCAR_temp" in script


# ---------- global_commands 测试 ----------
def test_global_commands():
    """测试全局命令列表"""
    commands = utils.global_commands()

    assert isinstance(commands, list)
    assert "AI    ->  Chat with the Masgent AI" in commands
    assert "New   ->  Start a new session" in commands
    assert "Back  ->  Return to previous menu" in commands
    assert "Main  ->  Return to main menu" in commands
    assert "Help  ->  Show available functions" in commands
    assert "Exit  ->  Quit the Masgent" in commands
    assert commands[0] == ""


# ---------- get_color_map 测试 ----------
def test_get_color_map():
    """测试颜色映射字典"""
    color_map = utils.get_color_map()

    assert isinstance(color_map, dict)
    assert "red" in color_map
    assert "green" in color_map
    assert "yellow" in color_map
    assert "blue" in color_map
    assert "magenta" in color_map
    assert "cyan" in color_map
    assert "white" in color_map


# ---------- color_print 和 color_input 测试 ----------
def test_color_print(capsys):
    """测试彩色打印函数"""
    utils.color_print("test message", "green")
    captured = capsys.readouterr()
    assert "test message" in captured.out


def test_color_input(monkeypatch):
    """测试彩色输入函数"""
    monkeypatch.setattr("builtins.input", lambda _: "user response")
    result = utils.color_input("Prompt: ", "cyan")
    assert result == "user response"


# ---------- create_deformation_matrices 测试 ----------
def test_create_deformation_matrices():
    """测试应变矩阵生成函数"""
    matrices = utils.create_deformation_matrices()

    assert isinstance(matrices, list)
    assert len(matrices) == 13

    zero_dict = matrices[0]
    zero_name = list(zero_dict.keys())[0]
    zero_matrix = zero_dict[zero_name]
    assert zero_name == "00_strain_0.000"
    assert zero_matrix == [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

    strain_dict = matrices[1]
    strain_name = list(strain_dict.keys())[0]
    strain_matrix = strain_dict[strain_name]
    assert "strain_xx" in strain_name
    assert strain_matrix[0][0] != 0


# ---------- load_system_prompts 测试 ----------
def test_load_system_prompts():
    """测试加载系统提示词"""
    result = utils.load_system_prompts()
    assert isinstance(result, str)


# ---------- print_banner 测试 ----------
def test_print_banner(capsys):
    """测试打印横幅（只验证不抛出异常）"""
    try:
        utils.print_banner()
        captured = capsys.readouterr()
        assert "Masgent" in captured.out or "Version" in captured.out
    except Exception as e:
        pytest.fail(f"print_banner raised an exception: {e}")


# ---------- exit_and_cleanup 测试 ----------
def test_exit_and_cleanup(tmp_path, monkeypatch):
    """测试 exit_and_cleanup 函数（非空目录）"""
    monkeypatch.setenv("MASGENT_SESSION_RUNS_DIR", str(tmp_path))
    (tmp_path / "file.txt").write_text("content")

    with pytest.raises(SystemExit) as exc_info:
        utils.exit_and_cleanup()
    assert exc_info.type == SystemExit
    assert exc_info.value.code == 0


def test_exit_and_cleanup_empty_dir(tmp_path, monkeypatch):
    """测试 exit_and_cleanup 函数（空目录被删除）"""
    monkeypatch.setenv("MASGENT_SESSION_RUNS_DIR", str(tmp_path))

    with pytest.raises(SystemExit) as exc_info:
        utils.exit_and_cleanup()
    assert exc_info.type == SystemExit
    assert not tmp_path.exists()


# ============================================================
# 以下函数涉及交互式输入或外部依赖，不进行单元测试：
# - visualize_structure: 生成 HTML 且依赖 3Dmol.js
# - start_new_session: 依赖 os.getcwd() 和实际文件系统
# - ask_for_api_key: 交互式输入
# - validate_mp_api_key: 依赖网络 API
# - ask_for_mp_api_key: 交互式输入
# - clear_and_print_*_message: 依赖系统命令和环境变量
# - print_help: 打印帮助信息
# ============================================================