"""VASP 相关工具：POSCAR 生成、输入准备、KPOINTS、坐标转换、工作流生成"""

import os, re, random, shutil
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Literal, List
from ase.io import read, write
from pymatgen.core import Structure, Lattice
from pymatgen.io.vasp import Poscar, Kpoints
from pymatgen.io.vasp.sets import MPStaticSet, MPRelaxSet, MPMetalRelaxSet, MPNonSCFSet, MPMDSet, NEBSet
from masgent.models import schemas
from masgent.utils import (
    write_comments, ask_for_mp_api_key, validate_mp_api_key,
    generate_submit_script, generate_batch_script, list_files_in_dir,
    fit_eos, create_deformation_matrices, visualize_structure
)
from masgent._config import config
from .core import with_metadata

_mp_key_checked = False


@with_metadata(schemas.ToolMetadata(
    name='Generate POSCARs from Materials Project',
    description='Generate all possible POSCAR files from Materials Project database based on chemical formula, with the most stable structure saved as POSCAR by default and all matched structures saved in a separate folder.',
    requires=['formula'],
    optional=[],
    defaults={},
    prereqs=[],
))
def generate_vasp_poscar(formula: str) -> dict:
    '''
    Generate VASP POSCAR file from Materials Project database.
    '''
    try:
        schemas.GenerateVaspPoscarSchema(formula=formula)
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }

    try:
        runs_dir = str(config.get_runs_dir())

        poscars_dir = os.path.join(runs_dir, f'POSCARs/{formula}')
        os.makedirs(poscars_dir, exist_ok=True)

        # Ensure Materials Project API key exists and validate it only once per process
        global _mp_key_checked
        if not config.mp_api_key:
            ask_for_mp_api_key()
            validate_mp_api_key(os.environ['MP_API_KEY'])
            _mp_key_checked = True
        
        from mp_api.client import MPRester
        with MPRester(mute_progress_bars=True) as mpr:
            docs = mpr.materials.summary.search(formula=formula)
            if not docs:
                return {
                    'status': 'error',
                    'message': f'No materials found in Materials Project database for formula: {formula}'
                }
            
            # Get all material_ids and their energy above hull
            mid_energy = {}
            for doc in docs:
                mid_energy[str(doc.material_id)] = doc.energy_above_hull
            # Sort by energy above hull
            sorted_mids = sorted(mid_energy.items(), key=lambda x: x[1])
            # Get the most stable structure
            mid_0 = sorted_mids[0][0]
            structure_0 = mpr.get_structure_by_material_id(mid_0, conventional_unit_cell=True)
            poscar_0 = Poscar(structure_0)
            # Save as POSCAR_{formula} and rewrite POSCAR
            poscar_0.write_file(os.path.join(runs_dir, 'POSCAR'), direct=True)
            poscar_0.write_file(os.path.join(runs_dir, f'POSCAR_{formula}'), direct=True)
            comments_0 = f'# (Most Stable) Generated by Masgent from Materials Project entry {mid_0}, crystal system: {docs[0].symmetry.crystal_system}, space group: {docs[0].symmetry.symbol}.'
            write_comments(os.path.join(runs_dir, 'POSCAR'), 'poscar', comments_0)
            write_comments(os.path.join(runs_dir, f'POSCAR_{formula}'), 'poscar', comments_0)
            
            # Save all matched structures in the poscars directory
            for doc in docs:
                mid = doc.material_id
                crystal_system = doc.symmetry.crystal_system
                space_group_symbol = doc.symmetry.symbol
                structure = mpr.get_structure_by_material_id(mid)
                poscar = Poscar(structure)

                # If "/" in space group symbol, replace with "_"
                space_group_symbol_ = space_group_symbol.replace('/', '_')
                poscar.write_file(os.path.join(poscars_dir, f'POSCAR_{crystal_system}_{space_group_symbol_}_{mid}'), direct=True)

                comments = f'# Generated by Masgent from Materials Project entry {mid}, crystal system: {crystal_system}, space group: {space_group_symbol}.'
                write_comments(os.path.join(poscars_dir, f'POSCAR_{crystal_system}_{space_group_symbol_}_{mid}'), 'poscar', comments)
        
        poscar_files = list_files_in_dir(poscars_dir) + [os.path.join(runs_dir, 'POSCAR')]
        
        return {
            'status': 'success',
            'message': f'Generated POSCAR(s) in {poscars_dir}.',
            'all_poscars': poscar_files,
            'most_stable_poscar': os.path.join(runs_dir, f'POSCAR_{formula}'),
        }

    except Exception as e:
        return {
            'status': 'error',
            'message': f'POSCAR generation failed: {str(e)}'
        }


@with_metadata(schemas.ToolMetadata(
    name='Generate VASP Inputs (INCAR, KPOINTS, POTCAR, POSCAR)',
    description='Generate VASP input files (INCAR, KPOINTS, POTCAR, POSCAR) from a given POSCAR file using pymatgen input sets (MPMetalRelaxSet, MPRelaxSet, MPStaticSet, MPNonSCFBandSet, MPNonSCFDOSSet, MPMDSet).',
    requires=['vasp_input_sets'],
    optional=['poscar_path', 'only_incar'],
    defaults={
        'poscar_path': 'current_session/POSCAR',
        'only_incar': False,
        },
    prereqs=[],
))
def generate_vasp_inputs_from_poscar(
    vasp_input_sets: str,
    poscar_path: str = None,
    only_incar: bool = False
) -> dict:
    '''
    Generate VASP input files (INCAR, KPOINTS, POTCAR, POSCAR) from a given POSCAR file using pymatgen input sets.
    '''
    from pymatgen.core import Structure
    if poscar_path is None: poscar_path = str(config.get_runs_dir() / "POSCAR")
    try:
        schemas.GenerateVaspInputsFromPoscar(
            poscar_path=poscar_path,
            vasp_input_sets=vasp_input_sets,
            only_incar=only_incar,
        )
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }

    VIS_MAP = {
        'MPMetalRelaxSet': MPMetalRelaxSet,
        'MPRelaxSet': MPRelaxSet,
        'MPStaticSet': MPStaticSet,
        'MPNonSCFBandSet': MPNonSCFSet,
        'MPNonSCFDOSSet': MPNonSCFSet,
        'MPMDSet': MPMDSet,
    }
    vis_class = VIS_MAP[vasp_input_sets]

    try:
        runs_dir = str(config.get_runs_dir())

        vasp_inputs_dir = os.path.join(runs_dir, f'vasp_inputs/{vasp_input_sets}')
        os.makedirs(vasp_inputs_dir, exist_ok=True)

        structure = Structure.from_file(poscar_path)
        
        if vasp_input_sets == 'MPRelaxSet':
            vis = vis_class(structure, user_incar_settings={'ISMEAR': 0})
        elif vasp_input_sets == 'MPNonSCFDOSSet':
            vis = vis_class(structure, mode='uniform', nedos=5000)
        else:
            vis = vis_class(structure)

        if only_incar:
            vis.incar.write_file(os.path.join(vasp_inputs_dir, 'INCAR'))
            vis.poscar.write_file(os.path.join(vasp_inputs_dir, 'POSCAR'))
            incar_comments = f'# Generated by Masgent using {vasp_input_sets} set provided by Materials Project.'
            write_comments(os.path.join(vasp_inputs_dir, 'INCAR'), 'incar', incar_comments)
            return {
                'status': 'success',
                'message': f'Generated INCAR based on {vasp_input_sets} in {os.path.join(vasp_inputs_dir, "INCAR")}.',
            }
        
        vis.incar.write_file(os.path.join(vasp_inputs_dir, 'INCAR'))
        vis.poscar.write_file(os.path.join(vasp_inputs_dir, 'POSCAR'))
        vis.kpoints.write_file(os.path.join(vasp_inputs_dir, 'KPOINTS'))
        vis.potcar.write_file(os.path.join(vasp_inputs_dir, 'POTCAR'))

        incar_comments = f'# Generated by Masgent using {vasp_input_sets} set provided by Materials Project.'
        write_comments(os.path.join(vasp_inputs_dir, 'INCAR'), 'incar', incar_comments)
        poscar_comments = f'# Generated by Masgent using {vasp_input_sets} set provided by Materials Project.'
        write_comments(os.path.join(vasp_inputs_dir, 'POSCAR'), 'poscar', poscar_comments)
        kpoints_comments = f'# Generated by Masgent using {vasp_input_sets} set provided by Materials Project.'
        write_comments(os.path.join(vasp_inputs_dir, 'KPOINTS'), 'kpoints', kpoints_comments)
        
        return {
            'status': 'success',
            'message': f'Generated VASP input files based on {vasp_input_sets} in {vasp_inputs_dir}.',
            'incar_path': os.path.join(vasp_inputs_dir, 'INCAR'),
            'kpoints_path': os.path.join(vasp_inputs_dir, 'KPOINTS'),
            'potcar_path': os.path.join(vasp_inputs_dir, 'POTCAR'),
            'poscar_path': os.path.join(vasp_inputs_dir, 'POSCAR'),
        }
    
    except Exception as e:
        return {
            'status': 'error',
            'message': f'VASP input files generation failed: {str(e)}'
        }


@with_metadata(schemas.ToolMetadata(
    name='Convert POSCAR Coordinates',
    description='Convert POSCAR between direct and cartesian coordinates.',
    requires=['to_cartesian'],
    optional=['poscar_path'],
    defaults={'poscar_path': 'current_session/POSCAR'},
    prereqs=[],
))
def convert_poscar_coordinates(
    to_cartesian: bool,
    poscar_path: str = None,
) -> dict:
    '''
    Convert POSCAR between direct and cartesian coordinates.
    '''
    from pymatgen.core import Structure
    if poscar_path is None: poscar_path = str(config.get_runs_dir() / "POSCAR")
    try:
        schemas.ConvertPoscarCoordinatesSchema(
            poscar_path=poscar_path,
            to_cartesian=to_cartesian,
        )
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }

    try:
        runs_dir = str(config.get_runs_dir())

        convert_dir = os.path.join(runs_dir, 'convert')
        os.makedirs(convert_dir, exist_ok=True)
        
        structure = Structure.from_file(poscar_path)
        poscar = Poscar(structure)
        poscar.write_file(os.path.join(convert_dir, 'POSCAR'), direct=not to_cartesian)
        coord_type = 'Cartesian' if to_cartesian else 'Direct'
        comments = f'# Generated by Masgent converted to {coord_type} coordinates.'
        write_comments(os.path.join(convert_dir, 'POSCAR'), 'poscar', comments)

        return {
            'status': 'success',
            'message': f'Converted POSCAR to {coord_type} coordinates in {os.path.join(convert_dir, "POSCAR")}.',
        }

    except Exception as e:
        return {
            'status': 'error',
            'message': f'POSCAR coordinate conversion failed: {str(e)}'
        }


@with_metadata(schemas.ToolMetadata(
    name='Customize KPOINTS',
    description='Customize VASP KPOINTS from POSCAR with specified accuracy level (Low, Medium, High, Custom).',
    requires=['accuracy_level'],
    optional=['poscar_path', 'custom_kppa', 'gamma_centered'],
    defaults={'poscar_path': 'current_session/POSCAR', 'custom_kppa': None, 'gamma_centered': True},
    prereqs=[],
))
def customize_vasp_kpoints_with_accuracy(
    accuracy_level: Literal['Low', 'Medium', 'High', 'Custom'],
    poscar_path: str = None,
    custom_kppa: int = None,
    gamma_centered: bool = True,
) -> dict:
    '''
    Customize VASP KPOINTS from POSCAR with specified accuracy level.
    '''
    from pymatgen.core import Structure
    if poscar_path is None: poscar_path = str(config.get_runs_dir() / "POSCAR")
    try:
        schemas.CustomizeVaspKpointsWithAccuracy(
            poscar_path=poscar_path,
            accuracy_level=accuracy_level,
        )
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }
    
    DENSITY_MAP = {
        'Low': 1000,
        'Medium': 3000,
        'High': 5000,
        'Custom': custom_kppa,
    }
    kppa = DENSITY_MAP[accuracy_level]

    try:
        runs_dir = str(config.get_runs_dir())
        
        structure = Structure.from_file(poscar_path)
        kpts = Kpoints.automatic_density(structure, kppa=kppa).kpts[0]
        if gamma_centered:
            kpoints = Kpoints.gamma_automatic(kpts=kpts)
        else:
            kpoints = Kpoints.monkhorst_automatic(kpts=kpts)
        kpoints.write_file(os.path.join(runs_dir, 'KPOINTS'))
        comments = f'# Generated by Masgent with {accuracy_level} accuracy (Grid Density = {kppa} / number of atoms)'
        write_comments(os.path.join(runs_dir, 'KPOINTS'), 'kpoints', comments)
        
        return {
            'status': 'success',
            'message': f'Updated KPOINTS with {accuracy_level} accuracy in {os.path.join(runs_dir, "KPOINTS")}.',
        }
    
    except Exception as e:
        return {
            'status': 'error',
            'message': f'VASP KPOINTS generation failed: {str(e)}'
        }


@with_metadata(schemas.ToolMetadata(
    name='Generate HPC Slurm Script',
    description='Generate HPC Slurm job submission script for VASP calculations.',
    requires=[],
    optional=['partition', 'nodes', 'ntasks', 'walltime', 'jobname', 'mail_type', 'mail_user', 'command'],
    defaults={
        'partition': 'normal',
        'nodes': 1,
        'ntasks': 8,
        'walltime': '01:00:00',
        'jobname': 'masgent_job',
        'command': 'srun vasp_std > vasp.out'
        },
    prereqs=[],
    ))
def generate_vasp_inputs_hpc_slurm_script(
    partition: str = 'normal',
    nodes: int = 1,
    ntasks: int = 8,
    walltime: str = '01:00:00',
    jobname: str = 'masgent_job',
    command: str = 'srun vasp_std > vasp.out'
) -> dict:
    '''
    Generate HPC Slurm job submission script for VASP calculations.
    '''
    try:
        schemas.GenerateVaspInputsHpcSlurmScript(
            partition=partition,
            nodes=nodes,
            ntasks=ntasks,
            walltime=walltime,
            jobname=jobname,
            command=command,
        )
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }

    try:
        runs_dir = str(config.get_runs_dir())
        
        scripts = f'''#!/bin/bash
#SBATCH --partition={partition}
#SBATCH --nodes={nodes}
#SBATCH --ntasks={ntasks}
#SBATCH --time={walltime}
#SBATCH --job-name={jobname}
#SBATCH --output={jobname}.out
#SBATCH --error={jobname}.err

# This Slurm script was generated by Masgent, customize as needed.
{command}
'''
        script_path = os.path.join(runs_dir, 'masgent_submit.sh')
        with open(script_path, 'w') as f:
            f.write(scripts)

        return {
            'status': 'success',
            'message': f'Generated Slurm script in {script_path}.',
        }
    
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Slurm script generation failed: {str(e)}'
        }


@with_metadata(schemas.ToolMetadata(
    name='Generate VASP input files and submit bash script for workflow of convergence tests',
    description='Generate VASP workflow of convergence tests for k-points and energy cutoff based on given POSCAR',
    requires=[],
    optional=['poscar_path', 'test_type', 'kpoint_levels', 'encut_levels'],
    defaults={
        'poscar_path': 'current_session/POSCAR',
        'test_type': 'both',
        'kpoint_levels': [1000, 2000, 3000, 4000, 5000],
        'encut_levels': [300, 400, 500, 600, 700],
        },
    prereqs=[],
))
def generate_vasp_workflow_of_convergence_tests(
    poscar_path: str = None,
    test_type: Literal['kpoints', 'encut', 'both'] = 'both',
    kpoint_levels: List[int] = [1000, 2000, 3000, 4000, 5000],
    encut_levels: List[int] = [300, 400, 500, 600, 700],
) -> dict:
    '''
    Generate VASP input files and submit bash script for workflow of convergence tests for k-points and energy cutoff based on given POSCAR
    '''
    if poscar_path is None: poscar_path = str(config.get_runs_dir() / "POSCAR")
    try:
        schemas.GenerateVaspWorkflowOfConvergenceTests(
            poscar_path=poscar_path,
            test_type=test_type,
            kpoint_levels=kpoint_levels,
            encut_levels=encut_levels,
        )
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }

    def test_kpoints():
        os.makedirs(kpoint_tests_dir, exist_ok=True)
        vis = MPStaticSet(structure)
        vis.incar.write_file(os.path.join(kpoint_tests_dir, 'INCAR_temp'))
        vis.potcar.write_file(os.path.join(kpoint_tests_dir, 'POTCAR_temp'))
        incar_comments = f'# Generated by Masgent for k-point convergence test.'
        write_comments(os.path.join(kpoint_tests_dir, 'INCAR_temp'), 'incar', incar_comments)
        script_path = os.path.join(kpoint_tests_dir, 'submit_temp.sh')
        script = generate_submit_script()
        with open(script_path, 'w') as f:
            f.write(script)

        for kppa in kpoint_levels:
            test_dir = os.path.join(kpoint_tests_dir, f'kppa_{kppa}')
            os.makedirs(test_dir, exist_ok=True)
            
            vis = MPStaticSet(structure)
            vis.poscar.write_file(os.path.join(test_dir, 'POSCAR'))
            poscar_comments = f'# Generated by Masgent for k-point convergence test with kppa = {kppa}.'
            write_comments(os.path.join(test_dir, 'POSCAR'), 'poscar', poscar_comments)
            kpoints = Kpoints.automatic_density(structure, kppa=kppa)
            kpoints.write_file(os.path.join(test_dir, 'KPOINTS'))
            kpoint_comments = f'# Generated by Masgent for k-point convergence test with kppa = {kppa}.'
            write_comments(os.path.join(test_dir, 'KPOINTS'), 'kpoints', kpoint_comments)

        batch_script_path = os.path.join(kpoint_tests_dir, 'RUN_ME.sh')
        batch_script = generate_batch_script(update_incar=True, update_kpoints=False)
        with open(batch_script_path, 'w') as f:
            f.write(batch_script)

    def test_encut():
        os.makedirs(encut_tests_dir, exist_ok=True)
        vis = MPStaticSet(structure)
        vis.kpoints.write_file(os.path.join(encut_tests_dir, 'KPOINTS_temp'))
        vis.potcar.write_file(os.path.join(encut_tests_dir, 'POTCAR_temp'))
        kpoint_comments = f'# Generated by Masgent for energy cutoff convergence test.'
        write_comments(os.path.join(encut_tests_dir, 'KPOINTS_temp'), 'kpoints', kpoint_comments)
        script_path = os.path.join(encut_tests_dir, 'submit_temp.sh')
        script = generate_submit_script()
        with open(script_path, 'w') as f:
            f.write(script)

        for encut in encut_levels:
            test_dir = os.path.join(encut_tests_dir, f'encut_{encut}')
            os.makedirs(test_dir, exist_ok=True)

            vis = MPStaticSet(structure, user_incar_settings={'ENCUT': encut})
            vis.incar.write_file(os.path.join(test_dir, 'INCAR'))
            incar_comments = f'# Generated by Masgent for energy cutoff convergence test with ENCUT = {encut}.'
            write_comments(os.path.join(test_dir, 'INCAR'), 'incar', incar_comments)
            vis.poscar.write_file(os.path.join(test_dir, 'POSCAR'))
            poscar_comments = f'# Generated by Masgent for energy cutoff convergence test with ENCUT = {encut}.'
            write_comments(os.path.join(test_dir, 'POSCAR'), 'poscar', poscar_comments)

        batch_script_path = os.path.join(encut_tests_dir, 'RUN_ME.sh')
        batch_script = generate_batch_script(update_incar=False, update_kpoints=True)
        with open(batch_script_path, 'w') as f:
            f.write(batch_script)

    try:
        runs_dir = str(config.get_runs_dir())
        
        convergence_tests_dir = os.path.join(runs_dir, 'convergence_tests')
        kpoint_tests_dir = os.path.join(convergence_tests_dir, 'kpoint_tests')
        encut_tests_dir = os.path.join(convergence_tests_dir, 'encut_tests')

        structure = Structure.from_file(poscar_path)

        if test_type == 'kpoints':
            test_kpoints()
        elif test_type == 'encut':
            test_encut()
        else:
            test_kpoints()
            test_encut()

        kpoint_tests_files = list_files_in_dir(kpoint_tests_dir) if os.path.exists(kpoint_tests_dir) else []
        encut_tests_files = list_files_in_dir(encut_tests_dir) if os.path.exists(encut_tests_dir) else []

        return {
            'status': 'success',
            'message': f'Generated VASP workflow of convergence tests of k-points in {kpoint_tests_dir} and energy cutoff in {encut_tests_dir}.',
            'kpoint_tests_files': kpoint_tests_files,
            'encut_tests_files': encut_tests_files,
        }
    
    except Exception as e:
        return {
            'status': 'error',
            'message': f'VASP convergence tests workflow generation failed: {str(e)}'
        }


@with_metadata(schemas.ToolMetadata(
    name='Generate VASP input files and submit bash script for workflow of equation of state (EOS) calculations',
    description='Generate VASP input files and submit bash script for workflow of equation of state (EOS) calculations based on given POSCAR',
    requires=[],
    optional=['poscar_path', 'scale_factors'],
    defaults={
        'poscar_path': 'current_session/POSCAR',
        'scale_factors': [0.94, 0.96, 0.98, 1.00, 1.02, 1.04, 1.06],
        },
    prereqs=[],
))
def generate_vasp_workflow_of_eos(
    poscar_path: str = None,
    scale_factors: List[float] = [0.94, 0.96, 0.98, 1.00, 1.02, 1.04, 1.06],
) -> dict:
    '''
    Generate VASP input files and submit bash script for workflow of equation of state (EOS) calculations based on given POSCAR
    '''
    from pymatgen.core import Structure
    if poscar_path is None: poscar_path = str(config.get_runs_dir() / "POSCAR")
    try:
        schemas.GenerateVaspWorkflowOfEos(
            poscar_path=poscar_path,
            scale_factors=scale_factors,
        )
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }

    try:
        runs_dir = str(config.get_runs_dir())
        
        eos_dir = os.path.join(runs_dir, 'eos_calculations')
        os.makedirs(eos_dir, exist_ok=True)
        
        structure = Structure.from_file(poscar_path)
        vis = MPStaticSet(structure)
        vis.incar.write_file(os.path.join(eos_dir, 'INCAR_temp'))
        vis.kpoints.write_file(os.path.join(eos_dir, 'KPOINTS_temp'))
        vis.potcar.write_file(os.path.join(eos_dir, 'POTCAR_temp'))
        incar_comments = f'# Generated by Masgent for EOS calculation'
        write_comments(os.path.join(eos_dir, 'INCAR_temp'), 'incar', incar_comments)
        kpoint_comments = f'# Generated by Masgent for EOS calculation'
        write_comments(os.path.join(eos_dir, 'KPOINTS_temp'), 'kpoints', kpoint_comments)
        script_path = os.path.join(eos_dir, 'submit_temp.sh')
        script = generate_submit_script()
        with open(script_path, 'w') as f:
            f.write(script)

        for scale in scale_factors:
            scaled_structure = structure.copy()
            scaled_structure.scale_lattice(structure.volume * scale)
            scale_dir = os.path.join(eos_dir, f'scale_{scale:.3f}')
            os.makedirs(scale_dir, exist_ok=True)
            
            vis = MPStaticSet(scaled_structure)
            vis.poscar.write_file(os.path.join(scale_dir, 'POSCAR'))
            poscar_comments = f'# Generated by Masgent for EOS calculation with scale factor = {scale:.3f}.'
            write_comments(os.path.join(scale_dir, 'POSCAR'), 'poscar', poscar_comments)

        batch_script_path = os.path.join(eos_dir, 'RUN_ME.sh')
        batch_script = generate_batch_script(update_incar=True, update_kpoints=True)
        with open(batch_script_path, 'w') as f:
            f.write(batch_script)
        
        eos_files = list_files_in_dir(eos_dir) if os.path.exists(eos_dir) else []

        return {
            'status': 'success',
            'message': f'Generated VASP workflow of EOS calculations in {eos_dir}.',
            'eos_files': eos_files,
        }
    
    except Exception as e:
        return {
            'status': 'error',
            'message': f'VASP EOS workflow generation failed: {str(e)}'
        }


@with_metadata(schemas.ToolMetadata(
    name='Generate VASP input files and submit bash script for workflow of elastic constants calculations',
    description='Generate VASP input files and submit bash script for workflow of elastic constants calculations based on given POSCAR',
    requires=[],
    optional=['poscar_path'],
    defaults={'poscar_path': 'current_session/POSCAR'},
    prereqs=[],
))
def generate_vasp_workflow_of_elastic_constants(
    poscar_path: str = None,
) -> dict:
    '''
    Generate VASP input files and submit bash script for workflow of elastic constants calculations based on given POSCAR
    '''
    from pymatgen.core import Structure
    if poscar_path is None: poscar_path = str(config.get_runs_dir() / "POSCAR")
    try:
        schemas.GenerateVaspWorkflowOfElasticConstants(poscar_path=poscar_path)
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }

    try:
        from pymatgen.core import Lattice
        runs_dir = str(config.get_runs_dir())
        
        elastic_dir = os.path.join(runs_dir, 'elastic_constants')
        os.makedirs(elastic_dir, exist_ok=True)
        
        structure = Structure.from_file(poscar_path)
        vis = MPStaticSet(structure, reciprocal_density=500)
        vis.incar.write_file(os.path.join(elastic_dir, 'INCAR_temp'))
        vis.kpoints.write_file(os.path.join(elastic_dir, 'KPOINTS_temp'))
        vis.potcar.write_file(os.path.join(elastic_dir, 'POTCAR_temp'))
        incar_comments = f'# Generated by Masgent for elastic constants calculation.'
        write_comments(os.path.join(elastic_dir, 'INCAR_temp'), 'incar', incar_comments)
        kpoint_comments = f'# Generated by Masgent for elastic constants calculation.'
        write_comments(os.path.join(elastic_dir, 'KPOINTS_temp'), 'kpoints', kpoint_comments)
        script_path = os.path.join(elastic_dir, 'submit_temp.sh')
        script = generate_submit_script()
        with open(script_path, 'w') as f:
            f.write(script)

        D_all = create_deformation_matrices()

        for D_dict in D_all:
            folder_name = list(D_dict.keys())[0]
            D = D_dict[folder_name]
            deformed_structure = structure.copy()
            F = np.eye(3) + np.array(D)
            deformed_lattice = Lattice(F @ structure.lattice.matrix)
            deformed_structure.lattice = deformed_lattice
            deform_dir = os.path.join(elastic_dir, folder_name)
            os.makedirs(deform_dir, exist_ok=True)
            
            vis = MPStaticSet(deformed_structure)
            vis.poscar.write_file(os.path.join(deform_dir, 'POSCAR'))
            poscar_comments = f'# Generated by Masgent for elastic constants calculation with deformation {folder_name}.'
            write_comments(os.path.join(deform_dir, 'POSCAR'), 'poscar', poscar_comments)
        
        batch_script_path = os.path.join(elastic_dir, 'RUN_ME.sh')
        batch_script = generate_batch_script(update_incar=True, update_kpoints=True)
        with open(batch_script_path, 'w') as f:
            f.write(batch_script)

        elastic_files = list_files_in_dir(elastic_dir) if os.path.exists(elastic_dir) else []

        return {
            'status': 'success',
            'message': f'Generated VASP workflow of elastic constants calculations in {elastic_dir}.',
            'elastic_files': elastic_files,
        }

    except Exception as e:
        return {
            'status': 'error',
            'message': f'VASP elastic constants workflow generation failed: {str(e)}'
        }


@with_metadata(schemas.ToolMetadata(
    name='Generate VASP input files and submit bash script for workflow of ab initio molecular dynamics (AIMD) simulation',
    description='Generate VASP input files and submit bash script for workflow of ab initio molecular dynamics (AIMD) simulations based on given POSCAR',
    requires=[],
    optional=['poscar_path', 'temperature', 'md_steps', 'md_timestep'],
    defaults={
        'poscar_path': 'current_session/POSCAR',
        'temperatures': [500, 1000, 1500, 2000, 2500],
        'md_steps': 1000,
        'md_timestep': 5.0,
        },
    prereqs=[],
))
def generate_vasp_workflow_of_aimd(
    poscar_path: str = None,
    temperatures: list[int] = [500, 1000, 1500, 2000, 2500],
    md_steps: int = 1000,
    md_timestep: float = 5.0,
    ) -> dict:
    '''
    Generate VASP input files and submit bash script for workflow of ab initio molecular dynamics (AIMD) simulations based on given POSCAR
    '''
    try:
        schemas.GenerateVaspWorkflowOfAimd(
            poscar_path=poscar_path,
            temperatures=temperatures,
            md_steps=md_steps,
            md_timestep=md_timestep,
        )
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }
    
    try:
        runs_dir = str(config.get_runs_dir())
        
        aimd_dir = os.path.join(runs_dir, 'aimd_simulations')
        os.makedirs(aimd_dir, exist_ok=True)
        
        structure = Structure.from_file(poscar_path)
        vis = MPMDSet(structure, start_temp=temperatures[0], end_temp=temperatures[0], nsteps=md_steps, time_step=md_timestep)
        vis.kpoints.write_file(os.path.join(aimd_dir, 'KPOINTS_temp'))
        vis.potcar.write_file(os.path.join(aimd_dir, 'POTCAR_temp'))
        kpoint_comments = f'# Generated by Masgent for AIMD simulation.'
        write_comments(os.path.join(aimd_dir, 'KPOINTS_temp'), 'kpoints', kpoint_comments)
        script_path = os.path.join(aimd_dir, 'submit_temp.sh')
        script = generate_submit_script()
        with open(script_path, 'w') as f:
            f.write(script)

        for temperature in temperatures:
            temp_dir = os.path.join(aimd_dir, f'T_{temperature}K')
            os.makedirs(temp_dir, exist_ok=True)

            vis = MPMDSet(structure, start_temp=temperature, end_temp=temperature, nsteps=md_steps, time_step=md_timestep)
            vis.incar.write_file(os.path.join(temp_dir, 'INCAR'))
            incar_comments = f'# Generated by Masgent for AIMD simulation at {temperature} K for {md_steps} steps with timestep {md_timestep} fs.'
            write_comments(os.path.join(temp_dir, 'INCAR'), 'incar', incar_comments)
            vis.poscar.write_file(os.path.join(temp_dir, 'POSCAR'))
            poscar_comments = f'# Generated by Masgent for AIMD simulation at {temperature} K for {md_steps} steps with timestep {md_timestep} fs.'
            write_comments(os.path.join(temp_dir, 'POSCAR'), 'poscar', poscar_comments)
        
        batch_script_path = os.path.join(aimd_dir, 'RUN_ME.sh')
        batch_script = generate_batch_script(update_incar=False, update_kpoints=True)
        with open(batch_script_path, 'w') as f:
            f.write(batch_script)

        aimd_files = list_files_in_dir(aimd_dir) if os.path.exists(aimd_dir) else []
        
        return {
            'status': 'success',
            'message': f'Generated VASP workflow of AIMD simulations in {aimd_dir}.',
            'aimd_files': aimd_files,
        }
    
    except Exception as e:
        return {
            'status': 'error',
            'message': f'VASP AIMD workflow generation failed: {str(e)}'
        }


@with_metadata(schemas.ToolMetadata(
    name='Generate VASP input files and submit bash script for workflow of nudged elastic band (NEB) calculations',
    description='Generate VASP input files and submit bash script for workflow of nudged elastic band (NEB) calculations based on given initial and final POSCARs',
    requires=['initial_poscar_path', 'final_poscar_path'],
    optional=['num_images'],
    defaults={'num_images': 5},
    prereqs=[],
))
def generate_vasp_workflow_of_neb(
        initial_poscar_path: str,
        final_poscar_path: str,
        num_images: int = 5,
    ) -> dict:
    '''
    Generate VASP input files and submit bash script for workflow of nudged elastic band (NEB) calculations based on given initial and final POSCARs
    '''
    try:
        schemas.GenerateVaspWorkflowOfNeb(
            initial_poscar_path=initial_poscar_path,
            final_poscar_path=final_poscar_path,
            num_images=num_images,
        )
    except Exception as e:
        return {
            'status': 'error',
            'message': f'Invalid input parameters: {str(e)}'
        }
    
    try:
        runs_dir = str(config.get_runs_dir())
        
        neb_dir = os.path.join(runs_dir, 'neb_calculations')
        os.makedirs(neb_dir, exist_ok=True)

        from ase.mep import NEB

        initial_atoms = read(initial_poscar_path, format='vasp')
        final_atoms = read(final_poscar_path, format='vasp')

        # Set the averaged cell to both structures
        initial_cell = initial_atoms.get_cell()
        final_cell = final_atoms.get_cell()
        average_cell = (initial_cell + final_cell) / 2
        initial_atoms.set_cell(average_cell, scale_atoms=True)
        final_atoms.set_cell(average_cell, scale_atoms=True)

        # Create NEB images
        images = [initial_atoms] + [initial_atoms.copy() for i in range(num_images)] + [final_atoms]
        neb = NEB(images, remove_rotation_and_translation=True)
        neb.interpolate()

        pmg_images = [Structure.from_ase_atoms(img) for img in images]
        vis = NEBSet(pmg_images, user_incar_settings={'LCLIMB': True, 'SPRING': -5})
        vis.incar.write_file(os.path.join(neb_dir, 'INCAR'))
        vis.kpoints.write_file(os.path.join(neb_dir, 'KPOINTS'))
        vis.potcar.write_file(os.path.join(neb_dir, 'POTCAR'))
        incar_comments = f'# Generated by Masgent for NEB calculation with {num_images} images.'
        write_comments(os.path.join(neb_dir, 'INCAR'), 'incar', incar_comments)
        kpoint_comments = f'# Generated by Masgent for NEB calculation with {num_images} images.'
        write_comments(os.path.join(neb_dir, 'KPOINTS'), 'kpoints', kpoint_comments)
        
        scripts = generate_submit_script()
        script_path = os.path.join(neb_dir, 'submit.sh')
        with open(script_path, 'w') as f:
            f.write(scripts)
        
        num_dirs = len(images)
        padding = max(2, len(str(num_dirs - 1)))
        for i, image in enumerate(images):
            image_dir = os.path.join(neb_dir, f'{i:0{padding}d}')
            os.makedirs(image_dir, exist_ok=True)
            write(os.path.join(image_dir, 'POSCAR'), image, format='vasp', direct=True, sort=True)
            poscar_comments = f'# Generated by Masgent for NEB calculation image {i}.'
            write_comments(os.path.join(image_dir, 'POSCAR'), 'poscar', poscar_comments)

        neb_files = list_files_in_dir(neb_dir) if os.path.exists(neb_dir) else []
        
        return {
            'status': 'success',
            'message': f'Generated VASP workflow of NEB calculations in {neb_dir}.',
            'neb_files': neb_files,
        }

    except Exception as e:
        return {
            'status': 'error',
            'message': f'VASP NEB workflow generation failed: {str(e)}'
        }
