"""文件与 I/O 辅助函数"""

import os


def list_files_in_dir(dir):
    """递归列出目录下所有文件"""
    all_files = []
    for root, _, files in os.walk(dir):
        for file in files:
            all_files.append(os.path.join(root, file))
    return all_files


def write_comments(file, file_type, comments):
    """向 POSCAR / INCAR / KPOINTS 写入注释"""
    with open(file, 'r') as f:
        lines = f.readlines()
    if file_type.lower() in {'poscar', 'kpoints'}:
        lines[0] = comments + '\n'
    elif file_type.lower() == 'incar':
        lines.insert(0, f'{comments}\n')
    with open(file, 'w') as f:
        f.writelines(lines)


def generate_submit_script():
    """生成 Slurm 提交脚本模板（单节点）"""
    return '''#!/bin/bash
#SBATCH --partition=normal
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --time=01:00:00
#SBATCH --job-name=masgent_job
#SBATCH --output=masgent_job.out
#SBATCH --error=masgent_job.err

# This Slurm script was generated by Masgent, customize as needed.

time srun vasp_std > vasp.out
'''


def generate_batch_script(update_incar=True, update_kpoints=True):
    """生成批量提交脚本（用于工作流）"""
    lines = [
        '#!/bin/bash\n',
        '\n# This script was generated by Masgent to update VASP input files and submit jobs.\n',
        '# After modifying the template files (INCAR_temp, KPOINTS_temp, POTCAR_temp,\n',
        '# and submit_temp.sh, if present), run:\n',
        '#   bash ./RUN_ME.sh\n',
        '\n# Update VASP inputs in each folder\n',
        'for d in */; do\n',
        '    cp POTCAR_temp  "$d/POTCAR"\n',
    ]
    if update_incar:
        lines.append('    cp INCAR_temp  "$d/INCAR"\n')
    if update_kpoints:
        lines.append('    cp KPOINTS_temp  "$d/KPOINTS"\n')
    lines.extend([
        'done\n',
        '\n# Update submit script and submit jobs in each folder\n',
        'for d in */; do\n',
        '    cp submit_temp.sh  "$d/submit.sh"\n',
        '    chmod +x "$d/submit.sh"\n',
        '    cd "$d"\n',
        '    sbatch submit.sh\n',
        '    cd ..\n',
        'done\n',
    ])
    return ''.join(lines)